---
name: 🤖 AI-Driven Issue
description: Just describe what you're thinking - AI will understand and standardize it
title: "[AI] "
labels: ["ai:triage"]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: Tell us what you're thinking
      description: Describe your idea, problem, or suggestion in your own words
      placeholder: |
        Examples:
        "I think the AI should remember what I built last time..."
        "The mod crashes when I ask it to teleport me..."
        "It would be cool if the AI could organize my inventory..."
        "The AI responses are too slow on my server..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Note:** We use AI to process this issue. Your data will be sent to AI services for analysis. Please ensure no sensitive information is included.
