---
name: 🔧 Enhancement
description: Suggest an improvement to existing functionality
title: "[Enhancement] "
labels: ["enhancement", "improvement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Version Information
        | Info | Details |
        |------|---------|
        | Mod Version | Please specify |
        | Minecraft Version | Please specify |
        | Fabric Version | Please specify |

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Describe how the feature currently works
      placeholder: Explain what happens now that you'd like to improve
    validations:
      required: true

  - type: textarea
    id: desired-behavior
    attributes:
      label: What would be better?
      description: Describe how you'd like it to work instead
      placeholder: Explain the improvement you're suggesting
    validations:
      required: true

  - type: textarea
    id: why-better
    attributes:
      label: Why would this be better?
      description: What benefits would this provide?
      placeholder: |
        - Makes it easier to...
        - Saves time because...
        - More intuitive because...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Give specific examples of when this would help
      placeholder: |
        Example situations:
        1. When I'm building and need to...
        2. During gameplay it would help if...

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details (Optional)
      description: Any technical suggestions or implementation ideas
      placeholder: Only fill this if you have technical knowledge about implementation
