---
name: ✨ Feature Request
description: Suggest a new feature for Keira mod
title: "[Feature] "
labels: ["type:feature"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Version Information
        | Info | Details |
        |------|---------|
        | Mod Version | Please specify |
        | Minecraft Version | Please specify |
        | Fabric Version | Please specify |

  - type: textarea
    id: feature-description
    attributes:
      label: What feature would you like?
      description: Describe the new feature you want to see
      placeholder: I would like the mod to be able to...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: What problem would this solve?
      description: Why do you need this feature?
      placeholder: This would help me because...
    validations:
      required: true

  - type: textarea
    id: how-it-works
    attributes:
      label: How should it work?
      description: Describe how you imagine using this feature
      placeholder: |
        When I do this... the AI should...
        The feature would work like...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Give specific examples of how you'd use this
      placeholder: |
        Example 1: When I'm mining, I could ask...
        Example 2: During building, it would help if...

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details (Optional)
      description: Any technical suggestions or implementation ideas
      placeholder: Only fill this if you have technical knowledge about implementation
