name: AI Issue Processing
description: Process AI-driven issues using Python

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  process-ai-issue:
    name: 📝 Process AI Issue
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'ai-processing')
    
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 🐍 Install Dependencies
        run: |
          pip install --no-cache-dir pyyaml requests
          # Optional AI libraries - install if needed
          pip install --no-cache-dir openai anthropic groq || echo "Optional AI libraries not installed"

      - name: 🤖 Process Issue with AI
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: python scripts/process_ai_issue.py

      - name: 📋 Update Issue with Python
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: python scripts/update_issue.py